# Generated by Django 3.2.7 on 2022-01-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_item_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='tagliaEU',
        ),
        migrations.AlterField(
            model_name='item',
            name='categoria',
            field=models.CharField(choices=[('S', 'Shojo'), ('SH', 'Shonen'), ('SE', ' Seinen'), ('I', 'Isekai'), ('A', 'Altro')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='condizioni',
            field=models.CharField(choices=[('N', 'New'), ('U', 'Used')], max_length=1),
        ),
    ]
